### PR TITLE
Make models overridable

### PR DESCRIPTION
**Pull request by colq2**
This MR enables to override the used models: `SentEmail` and `SentEmailUrlClicked`.

It adds static properties to the MailTracker class, which holds the classes of the models. Here is how it works:

```php
// overriding models
MailTracker::useSentEmailModel(OwnSentEmail::class);
MailTracker::useSentEmailUrlClickedModel(OwnSentEmailUrlClicked::class);

// creating models
$sentEmail = MailTracker::sentEmailModel();
$sentEmailUrlClicked = MailTracker::sentEmailUrlClickedModel();

// accessing classes
MailTracker::$sentEmailModel
MailTracker::$sentEmailUrlClickedModel
```

This pattern is well known across the Laravel ecosystem like in Laravel Passport (Passport::useTokenModel).

I updated the readme and added tests for this.

### CODE REVIEW

**Comment by colq2** [comment]
One thing we could consider:

Type hinting is a bit tricky. For example, in the events we are still type hinting the SentEmail class. In most cases, this should be fine, because usually the model is extended. In some cases, the developer would not extend the model and use a totally different model. The events would break.

The solution is to create an interface `SentModelInterface` and a trait `IsSentModel`, which can be used like this:

```php
class OwnSentEmail extends SomeAbstractModel implements SentModelInterface {
  use IsSentModel;
}
```

Most often you find this when applications have some sort of a custom abstract model, which every other model needs to extend.

What do you think? I would be fine implementing this here

**Comment by jdavidbakr** [comment]
I like it - I agree, making it a trait would be a good plan and as you say it follows the accepted Laravel pattern.

**Comment by colq2** [comment]
PR is ready 😎

I type hint the model now with `Model|SentEmailModel`.

With PHP 8.2 we will have the nice possibility to use the DNF type for this: `Model&SentEmailModel`. But this is something for the future.

I also added a test for deleting the file, because I use the boot method in the trait to register a deleting listener and I wanted to ensure that it is deleting the file properly.

**Comment by jdavidbakr** [comment]
@colq2 can you please check on the conflicts

**Comment by colq2** [comment]
Sure! Where can I see the conflicts? I got a green check with "This branch has no conflicts with the base branch" on it.

**Comment by jdavidbakr** [comment]
That's odd, it shows me "This branch cannot be rebased due to conflicts" - maybe just do a pull from my master and merge it in just to make sure you're on the latest commit.

**Comment by colq2** [comment]
Hey @jdavidbakr, I pulled every change und merged into this PR but everything was up to date. Can you check again if you can merge it now?

**Comment by jdavidbakr** [comment]
I was able to merge it via the command line.  Not sure why the UI was blocking it.

**Pull request merged**
