### PR TITLE
Added ability to set custom content size limit from config file.

### PR DESCRIPTION
**Pull request by pavelsosipovs**
Based on following issue:
https://github.com/jdavidbakr/mail-tracker/issues/124
In short, added ability to set bigger length for `content` field.

### CODE REVIEW

**Comment by pavelsosipovs** [comment]
HI!
As I see from errors log at https://travis-ci.com/github/jdavidbakr/mail-tracker/jobs/459433114, here is unrelated to my changes error. Some related to composer packages. Should we wait till you will fix it?

**Comment by jdavidbakr** [comment]
Looks like there was a package in the Travis script that is not Composer 2.0 compatible.  I have removed it, please rebase on master and try again.

**Comment by pavelsosipovs** [comment]
All is done.

**Comment by jdavidbakr** [comment]
Thanks!

**Pull request merged**
