### PR TITLE
fix for inject links with urls having a ' in the path

### PR DESCRIPTION
**Pull request by ivang76**

### CODE REVIEW

**Comment by jdavidbakr** [comment]
Thanks, can you add a test for this change?

**Comment by ivang76** [comment]
I tested on my projects and server but tell me if you need something else

**Comment by jdavidbakr** [comment]
There needs to be a phpunit test in the tests/MailTrackerTest.php file that fails without your change but passes with your change.  You can run the tests with `vendor/bin/phpunit`

**Comment by jdavidbakr** [comment]
You could probably duplicate the `it_handles_ampersands_in_links` test and create a new test email with your use case

**Comment by ivang76** [comment]
I never used phpunit to make test, so I'm gonna try to understand quickly how to use it...

**Comment by ivang76** [comment]
Hi @jdavidbakr 
I added the phpunittest and done a commit... do you see it or should I open another pr now?

**Comment by jdavidbakr** [comment]
You should be able to push it to your repo and it automatically update the pull request.

**Comment by ivang76** [comment]
ok done... let me know

**Comment by jdavidbakr** [comment]
Looks like your test didn't pass

**Comment by ivang76** [comment]
can you help me a bit to sort it out? as I told you I'm not used to phpunit tests

**Comment by ivang76** [comment]
I have problems with my version of laravel and Orchestra\Testbench\TestCase... could you have a look and close this phpunit test so that the fix can be merged? 
Actually I'm still using my fix in prod without problem but in this way I can't update the vendors...
thanks

**Comment by jdavidbakr** [comment]
Your issue is that lines 689-691 of the test is expecting there to be two links in your email.  Note that the TestAmpersand.blade.php has a link without the ampersand, but your testApostrophe.blade.php doesn't have that.  You can just change line 691 to be `$aLink = $links[0]`.

Ideally with TDD you will write the test first, get a fail (it would have failed on line 698), and then write the code to get the test to pass.

**Comment by ivang76** [comment]
ok done

**Comment by jdavidbakr** [comment]
Thanks - released version 4.0.6

**Pull request merged**
