### PR TITLE
Master

### PR DESCRIPTION
**Pull request by amamarul**
Hello David,
I add a url clicked tracking to your mail-tracker.
I hope you like it.
Regards
Maru

### CODE REVIEW

**Comment by jdavidbakr** [comment]
Nice - would you mind adding some tests as well?  See test/MailTrackerTest.php to see the tests on the existing calls for reference.

**Comment by amamarul** [comment]
Hello, I´m working in an simple admin panel and i made a pair of simple views because i`m implementing an standard email test.
i didn`t finish yet but then i´ll make an other pull request.
Really i hope you like my job, i like this package very much because is very simple and is just i need.
Regards,
Maru

**Comment by jdavidbakr** [comment]
Thanks for your work - I was hoping someone would come along to build out the admin panel.  Please do make sure you have unit tests for everything.

**Comment by amamarul** [comment]
Hello, 
I already made a basic admin panel, then I will make the pull request and I would like, if you got time, to review what I did.
I need to add some things to the Readme, then I´ll do.
Of course thanks for publish this package
Regards,
Maru

**Comment by amamarul** [comment]
Hello David,
I add the admin panel and more, we have a "This branch has conflicts that must be resolved" and I think that is in the routes you change but I add routes names to use in the aplication.
Again I hope you like, the admin panel is very very simple but they may be modified.
I update de README too, english is not my native language and maybe you can improve.
Regards,
Maru

**Comment by jdavidbakr** [comment]
I have merged in your updates, thank you!  I changed your pages to use bootstrap and also added a search and pagination on your index page.

**Pull request merged**
