### PR TITLE
Update SNSController.php

### PR DESCRIPTION
**Pull request by AndrewRadchenko**
In case of SNS Complaint event type changed to ComplaintMessageEvent

### CODE REVIEW

**Comment by jdavidbakr** [comment]
We probably need to fire both events, since a complaint is a permanent bounce and removing the permanent bounce would be a breaking change.

Also, please fix the tests and update the readme.

**Comment by AndrewRadchenko** [comment]
I think that complaint is when recipient mark email as a spam (or email is a spamtrap). It means, that address is valid and ready to receive emails but recipient mark the email is spam.  So these emails are not bounced.
Permanent bounced is when address is wrong and there are no chance to deliver email.
So permanent bounce and complaint are different events.

**Comment by connecteev** [comment]
@AndrewRadchenko @jdavidbakr going to quickly chime in here..
1. I agree with @jdavidbakr,  the readme / tests would need to be updated if the event name changes.
2. I also agree with @AndrewRadchenko in that a complaint event and bounced event are 2 different things. Looking at the code here:
```
    protected function process_notification($message)
    {
        $message = json_decode($message->offsetGet('Message'));
        switch ($message->notificationType) {
            case 'Delivery':
                $this->process_delivery($message);
                break;
            case 'Bounce':
                $this->process_bounce($message);
                if ($message->bounce->bounceType == 'Permanent') {
                    foreach ($message->bounce->bouncedRecipients as $recipient) {
                        Event::dispatch(new PermanentBouncedMessageEvent($recipient->emailAddress));
                    }
                }
                break;
            case 'Complaint':
                $this->process_complaint($message);
                foreach ($message->complaint->complainedRecipients as $recipient) {
                    Event::dispatch(new PermanentBouncedMessageEvent($recipient->emailAddress));
                }
                break;
        }
```
they should not be treated the same IMO. 

3. Btw If this ends up being a breaking change instead of firing 2 events, maybe we can just bump up the version number and update the readme, since it will be cleaner and more maintainable?

4. While we're at it can we fire another event on Delivery (before calling $this->process_delivery)? It would make things consistent and the event listener may want to do some additional processing with that event (mark the email address as good / delivered, for example).

**Comment by jdavidbakr** [comment]
I can agree with those points, and that it would be a major revision update.

**Comment by connecteev** [comment]
@jdavidbakr Awesome. @AndrewRadchenko can you please make these changes? Thanks for the PR!

**Comment by jdavidbakr** [comment]
Closing in favor of https://github.com/jdavidbakr/mail-tracker/pull/92

**Pull request closed without merging**
