### PR TITLE
Fires distinct events for complaint, bounce and delivered emails afte…

### PR DESCRIPTION
**Pull request by connecteev**
- Fires distinct events for complaint, bounce and delivered emails after SNS notifications received
- Adds a breaking change (event name) when firing Complaint email SNS notifications (so I'd probably create a new release with a major version change instead of hacking and double-firing events)
- Fires bounce events with extra data (sent_email and email recipient).
- Stores the full SNS messages received (for bounce, delivery, complaint) in the sent_emails.meta field
- Better error handling (also tested): Fires events received from SNS, even if sent_email is not found in the DB
- Updated readme with more details
- Updated existing unit test
- Note: Tested extensively with real SNS notifications. No unit tests were run.

Note: The code in process_delivery(), process_bounce(), process_complaint() are assuming that each email was sent to ONE receipient. This may not be true.
For example you could do this:
```
    Mail::to("complaint@simulator.amazonses.com")
        ->cc(["success@simulator.amazonses.com", "bounce@simulator.amazonses.com"])
        ->send($message)
```
So we cannot set "success" to true or false, like we are now. What happens if one email receipient gets a successful delivery, and the other bounces, or complains? Then you have a race condition. Same with the other metadata. However, I am not going to touch that. For now, better to append the meta field with every SNS message that was received...so we have a record of every correspondence from SNS.
I'm not sure what a more elegant long-term fix is (ideally we would have separate entries in sent_emails for each email recipient, but I leave that to you). Also, feel free to add unit tests if you so choose, I couldn't get them to run.

Sample SNS logs:
```
[2019-11-03 05:46:49] local.EMERGENCY: {"place":2,"message":{"notificationType":"Delivery","mail":{"timestamp":"2019-11-03T05:46:45.603Z","source":"support@mydomain.com","sourceArn":"arn:aws:ses:us-west-2:753511209472:identity\/mydomain.com","sourceIp":"76.14.181.19","sendingAccountId":"753511209472","messageId":"0101016e2fcd2be3-e5aa8aa0-e34c-4efd-b16e-bdb2795b1921-000000","destination":["bounce@simulator.amazonses.com","complaint@simulator.amazonses.com","success@simulator.amazonses.com"]},"delivery":{"timestamp":"2019-11-03T05:46:46.985Z","processingTimeMillis":1382,"recipients":["complaint@simulator.amazonses.com","success@simulator.amazonses.com"],"smtpResponse":"250 2.6.0 Message received","remoteMtaIp":"34.235.192.246","reportingMTA":"a27-206.smtp-out.us-west-2.amazonses.com"}}}  

[2019-11-03 05:46:49] local.EMERGENCY: {"place":2,"message":{"notificationType":"Bounce","bounce":{"bounceType":"Permanent","bounceSubType":"General","bouncedRecipients":[{"emailAddress":"bounce@simulator.amazonses.com","action":"failed","status":"5.1.1","diagnosticCode":"smtp; 550 5.1.1 user unknown"}],"timestamp":"2019-11-03T05:46:47.072Z","feedbackId":"0101016e2fcd3168-0aedd039-fcbb-499f-aa32-d044b18711bc-000000","remoteMtaIp":"34.235.192.246","reportingMTA":"dsn; a27-206.smtp-out.us-west-2.amazonses.com"},"mail":{"timestamp":"2019-11-03T05:46:45.000Z","source":"support@mydomain.com","sourceArn":"arn:aws:ses:us-west-2:753511209472:identity\/mydomain.com","sourceIp":"76.14.181.19","sendingAccountId":"753511209472","messageId":"0101016e2fcd2be3-e5aa8aa0-e34c-4efd-b16e-bdb2795b1921-000000","destination":["complaint@simulator.amazonses.com","success@simulator.amazonses.com","bounce@simulator.amazonses.com"]}}}  

[2019-11-03 05:46:50] local.EMERGENCY: {"place":2,"message":{"notificationType":"Complaint","complaint":{"complaintSubType":null,"complainedRecipients":[{"emailAddress":"complaint@simulator.amazonses.com"}],"timestamp":"2019-11-03T05:46:46.000Z","feedbackId":"0101016e2fcd35b3-909cfd81-46a8-4d05-b0c4-e09e1369f126-000000","userAgent":"Amazon SES Mailbox Simulator","complaintFeedbackType":"abuse"},"mail":{"timestamp":"2019-11-03T05:46:41.000Z","source":"support@mydomain.com","sourceArn":"arn:aws:ses:us-west-2:753511209472:identity\/mydomain.com","sourceIp":"76.14.181.19","sendingAccountId":"753511209472","messageId":"0101016e2fcd2be3-e5aa8aa0-e34c-4efd-b16e-bdb2795b1921-000000","destination":["complaint@simulator.amazonses.com","success@simulator.amazonses.com","bounce@simulator.amazonses.com"]}}}  
```

### CODE REVIEW

**Comment by connecteev** [comment]
@jdavidbakr any thoughts on this PR? Spent an entire day on this, to be honest. I hope you like it and that it gets integrated into the package.

**Comment by jdavidbakr** [comment]
I do, I want to review it before merging it and haven't had a chance to.

**Comment by connecteev** [comment]
@jdavidbakr great, thank you

**Comment by jdavidbakr** [comment]
Released in 3.0.0

**Pull request merged**
